name: 'Giedre & Sebastian'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5190085843205452
title: 'G&S'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0b0b'
    - '#6c6c62'
    - '#eac5a8'
    - '#c24033'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
